name = "splendid_maroon_donkey-352d"
version = "1.0.0"

[deployment]
permission = "public"
nodes = 1

[build]
dir = "build"
entry = "splendid_maroon_donkey-352d_debug.wasm"
command = "npm run build:debug"

[build_release]
dir = "build"
entry = "splendid_maroon_donkey-352d.wasm"
command = "npm run build:release"
